p_set_03 : plurality runoff tideman

plurality : plurality.c
	cc -g -lcs50 -o plurality plurality.c

runoff : runoff.c
	cc -g -lcs50 -o runoff runoff.c

tideman : tideman.c
	cc -g -lcs50 -o tideman tideman.c
