p_set_01 : hello mario_less mario_more cash

hello : hello.c
	cc -lcs50 -o hello hello.c

mario_less : mario_less.c
	cc -lcs50 -o mario_less mario_less.c

mario_more : mario_more.c
	cc -lcs50 -o mario_more mario_more.c

cash : cash.c
	cc -lcs50 -o cash cash.c
