p_set_02 : caesar readability substitution

caesar : caesar.c
	cc -g -lcs50 -o caesar caesar.c

readability : readability.c
	cc -g -lcs50 -o readability readability.c

substitution : substitution.c
	cc -g -lcs50 -o substitution substitution.c
